### ISSUE TITLE
Dorst

### ISSUE THREAD

**Issue by koenhendriks** [serioushomebrew/KpnHackathon#2]
Ik lust wel wat drinken, er staat Red Bull in de koelkast

**Comment by peterschriever** [comment]
I will start looking into this.

**Comment by peterschriever** [comment]
![1460235032846-1288686663](https://cloud.githubusercontent.com/assets/6523141/14406351/7d9961e2-fea5-11e5-9bbc-375d631c8a10.jpg)

**Comment by kevinvdburgt** [comment]
![5ac924f1-df59-472f-a52a-d8d07c4d04c2](https://cloud.githubusercontent.com/assets/1987802/14406579/6f2e29d8-feac-11e5-9de0-6776599be619.jpg)
